name: Release drafter

on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install build tools
        run: |
          python -m pip install --upgrade build
      - name: Build project for distribution
        run: |
          python -m build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          # generate_release_notes: true
          files: |
            dist/*
